#!/bin/sh

# Be prepared to turn your laptop or desktop
# into an awesome development machine.

# Helpful functions
fancy_echo() {
  local fmt="$1"; shift

  # shellcheck disable=SC2059
  printf "\\n$fmt\\n" "$@"
}

# Brew : The missing package manager for macOS
# https://brew.sh/
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

# Git
brew install git

# mas-cli : A simple command line interface for the Mac App Store. Designed for scripting and automation.
# https://github.com/mas-cli/mas
brew install mas

# Zsh and prezto
brew install zsh
# Prezto : https://github.com/sorin-ionescu/prezto
/bin/zsh -c '
git clone --recursive https://github.com/dguera/prezto.git "${ZDOTDIR:-$HOME}/.zprezto"
setopt EXTENDED_GLOB
for rcfile in "${ZDOTDIR:-$HOME}"/.zprezto/runcoms/^README.md(.N); do
  ln -s "$rcfile" "${ZDOTDIR:-$HOME}/.${rcfile:t}"
done
chsh -s /bin/zsh'

# Install prezto contrib
cd $ZPREZTODIR
git clone --recurse-submodules https://github.com/belak/prezto-contrib contrib
cd -

if brew list | grep -Fq brew-cask; then
  fancy_echo "Uninstalling old Homebrew-Cask ..."
  brew uninstall --force brew-cask
fi

fancy_echo "Updating Homebrew formulae ..."
brew update --force # https://github.com/Homebrew/brew/issues/1151
brew bundle --file=- <<EOF
tap "homebrew/services"
tap "fabianishere/personal"

# Unix
brew "git"
brew "openssl"
brew "the_silver_searcher"
brew "tmux"
brew "vim"
brew "zsh"

# GitHub
brew "hub"

# Image manipulation
brew "imagemagick"

# Programming language prerequisites and package managers
brew "coreutils"
brew "thefuck"

# Enable touch id with sudo on iTerm 2
brew "pam_reattach"

# Casks
cask "iterm2"
cask "anaconda"
cask "anki"
cask "bartender"
cask "bettertouchtool"
cask "contexts"
cask "istat-menus"
cask "mactex"
cask "mendeley-desktop"
cask "osxfuse"
cask "spotify"
cask "sublime-text"
cask "tikzit"
cask "typora"
cask "visual-studio-code"
EOF

# Install font for iTerm2
cd ~/Library/Fonts && { curl -O 'https://github.com/nathco/Office-Code-Pro/raw/master/Fonts/Office%20Code%20Pro/OTF/' ; cd -; }
